/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Arreglo.ArregloHotel;
import clases.*;
import javax.swing.table.DefaultTableModel;
import listas.*;

/**
 *
 * @author Valia
 */
public class FormHoteles extends javax.swing.JInternalFrame {
    Arreglo.ArregloHotel objho =new ArregloHotel();
    listaHotel objh= new listaHotel();
    listaHabitacion obja = new listaHabitacion();
    /**
     * Creates new form FormHoteles
     */
    public FormHoteles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAgregarHotel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarHotel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnListarHotel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnActualizarHotel = new javax.swing.JButton();
        txtCodHotel = new javax.swing.JTextField();
        txtNomHotel = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        txthabitaciones = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHotel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarHotel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodHoHa = new javax.swing.JTextField();
        txtCodHabitacion = new javax.swing.JTextField();
        txtEstadoHab = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHabitacion = new javax.swing.JTable();
        btnBuscarHab = new javax.swing.JButton();
        btnAgregarHab = new javax.swing.JButton();
        btnEliminarHab = new javax.swing.JButton();
        btnActualizarHab = new javax.swing.JButton();
        btnListarHab = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setTitle("VentanaHotel");
        setVisible(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("LUGAR:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 110, 17);

        btnAgregarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/agregar.png"))); // NOI18N
        btnAgregarHotel.setText("AGREGAR");
        btnAgregarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarHotel);
        btnAgregarHotel.setBounds(650, 130, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 170, 110, 17);

        btnEliminarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/delete.png"))); // NOI18N
        btnEliminarHotel.setText("ELIMINAR");
        btnEliminarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarHotel);
        btnEliminarHotel.setBounds(650, 180, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CATEGORÍA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 220, 130, 17);

        btnListarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/listar.png"))); // NOI18N
        btnListarHotel.setText("LISTAR");
        btnListarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarHotel);
        btnListarHotel.setBounds(30, 350, 140, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("N° HABITACIONES:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 260, 160, 17);

        btnActualizarHotel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnActualizarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8-update-40.png"))); // NOI18N
        btnActualizarHotel.setText("ACTUALIZAR");
        btnActualizarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarHotel);
        btnActualizarHotel.setBounds(650, 220, 139, 50);
        getContentPane().add(txtCodHotel);
        txtCodHotel.setBounds(450, 90, 100, 30);
        getContentPane().add(txtNomHotel);
        txtNomHotel.setBounds(210, 170, 340, 30);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N° ESTRELLAS", "2", "3", "4", "5" }));
        getContentPane().add(cmbCategoria);
        cmbCategoria.setBounds(450, 210, 100, 30);
        getContentPane().add(txthabitaciones);
        txthabitaciones.setBounds(450, 250, 102, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PRECIO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 300, 90, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ESTADO:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(840, 220, 160, 17);
        getContentPane().add(txtLugar);
        txtLugar.setBounds(450, 130, 100, 30);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(450, 290, 100, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 25)); // NOI18N
        jLabel9.setText("HABITACIONES");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(820, 70, 230, 40);

        tableHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "LUGAR", "NOMBRES", "CATEGORIA", "PRECIO", "N° HABITACIONES"
            }
        ));
        jScrollPane1.setViewportView(tableHotel);
        if (tableHotel.getColumnModel().getColumnCount() > 0) {
            tableHotel.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
            tableHotel.getColumnModel().getColumn(1).setHeaderValue("LUGAR");
            tableHotel.getColumnModel().getColumn(2).setHeaderValue("NOMBRES");
            tableHotel.getColumnModel().getColumn(3).setHeaderValue("CATEGORIA");
            tableHotel.getColumnModel().getColumn(4).setHeaderValue("PRECIO");
            tableHotel.getColumnModel().getColumn(5).setHeaderValue("N° HABITACIONES");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 410, 673, 170);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel1.setText("HOTELES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 11, 137, 40);

        btnBuscarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/buscar.png"))); // NOI18N
        btnBuscarHotel.setText("BUSCAR");
        btnBuscarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarHotel);
        btnBuscarHotel.setBounds(650, 80, 140, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 59, 1410, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CÓDIGO:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 90, 110, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CÓDIGO HABITACION:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(830, 140, 180, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("CÓDIGO HOTEL:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(830, 180, 160, 17);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/fonthotel.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 620);
        getContentPane().add(txtCodHoHa);
        txtCodHoHa.setBounds(1020, 130, 100, 30);
        getContentPane().add(txtCodHabitacion);
        txtCodHabitacion.setBounds(1020, 170, 100, 30);
        getContentPane().add(txtEstadoHab);
        txtEstadoHab.setBounds(1020, 210, 100, 30);

        tablaHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "COD. HABITACION", "ESTADO"
            }
        ));
        jScrollPane2.setViewportView(tablaHabitacion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(860, 350, 452, 260);

        btnBuscarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/buscar.png"))); // NOI18N
        btnBuscarHab.setText("BUSCAR");
        btnBuscarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarHab);
        btnBuscarHab.setBounds(1180, 90, 150, 50);

        btnAgregarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/agregar.png"))); // NOI18N
        btnAgregarHab.setText("AGREGAR");
        btnAgregarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarHab);
        btnAgregarHab.setBounds(1180, 140, 150, 50);

        btnEliminarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/delete.png"))); // NOI18N
        btnEliminarHab.setText("ELIMINAR");
        btnEliminarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarHab);
        btnEliminarHab.setBounds(1180, 190, 150, 40);

        btnActualizarHab.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnActualizarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/actualizar.png"))); // NOI18N
        btnActualizarHab.setText("ACTUALIZAR");
        btnActualizarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarHab);
        btnActualizarHab.setBounds(1180, 230, 150, 40);

        btnListarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/listar.png"))); // NOI18N
        btnListarHab.setText("LISTAR");
        btnListarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarHab);
        btnListarHab.setBounds(840, 290, 130, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/fonthabitacion.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(800, 0, 560, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHotelActionPerformed
    int cod=Integer.parseInt(txtCodHotel.getText());
        Hotel h=objh.buscar(objh.obtenerPosicion(cod));
        limpiaTabla();
        if(h.getCodigo()==cod)
        tableHotel.setValueAt("H"+h.getCodigo(), 0, 0);
        tableHotel.setValueAt(h.getLugar(), 0, 1);
        tableHotel.setValueAt(h.getNomHotel(), 0, 2);
        tableHotel.setValueAt(h.getCategoria(), 0, 3);
        tableHotel.setValueAt(h.calcularCostoServicio(), 0, 4);
        tableHotel.setValueAt(h.getHabitaciones(), 0, 5);
        
        txtLugar.setText(h.getLugar());
        txtNomHotel.setText(h.getNomHotel());
        cmbCategoria.setSelectedItem(""+h.getCategoria());
        txthabitaciones.setText(""+h.getHabitaciones());
        txtPrecio.setText(""+h.getCostohotel());
    }//GEN-LAST:event_btnBuscarHotelActionPerformed

    private void btnListarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarHotelActionPerformed
        DefaultTableModel dt=(DefaultTableModel)tableHotel.getModel();
       dt.setRowCount(0);
       for(Hotel h: objh.data()){
            Object v[]={"H"+h.getCodigo(),h.getLugar(),h.getNomHotel(),h.getCategoria(),h.calcularCostoServicio(),h.getHabitaciones()};
            dt.addRow(v);
        }
    }//GEN-LAST:event_btnListarHotelActionPerformed

    private void btnAgregarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHotelActionPerformed
        String lugar = txtLugar.getText();
        String nombre = txtNomHotel.getText();
        String categoria = (String)cmbCategoria.getSelectedItem();
        int habitacion = Integer.parseInt(txthabitaciones.getText());
        int precio = Integer.parseInt(txtPrecio.getText());
        Hotel h = new Hotel(nombre, categoria, lugar, habitacion, precio, "HOTEL");
        objh.agregar(h);
        limpiarCamposHotel();
        listarHotel();
    }//GEN-LAST:event_btnAgregarHotelActionPerformed

    private void btnListarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarHabActionPerformed
        DefaultTableModel dt=(DefaultTableModel)tablaHabitacion.getModel();
       dt.setRowCount(0);
       for( Habitacion a: obja.data()){
            Object v[]={"V"+a.getCod_hotel(),"A"+a.getCod_habi(),a.getEstado()};
            dt.addRow(v);
        }
    }//GEN-LAST:event_btnListarHabActionPerformed

    private void btnBuscarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabActionPerformed
        int cod=Integer.parseInt(txtCodHoHa.getText());
        Habitacion ha=obja.buscar(obja.obtenerPosicion(cod));
        limpiaTabla();
        if(ha.getCod_hotel()==cod)
        tablaHabitacion.setValueAt(ha.getCod_hotel(), 0, 0);
        tablaHabitacion.setValueAt(ha.getCod_habi(), 0, 1);
        tablaHabitacion.setValueAt(ha.getEstado(), 0, 2);

        
        txtCodHoHa.setText(""+ha.getCod_hotel());
        txtCodHabitacion.setText(""+ha.getCod_habi());
        txtEstadoHab.setText(ha.getEstado());
    }//GEN-LAST:event_btnBuscarHabActionPerformed

    private void btnAgregarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHabActionPerformed
        int codHotel = Integer.parseInt(txtCodHoHa.getText());
        String estado = txtEstadoHab.getText();
        Habitacion ha =new Habitacion(codHotel, estado);
        obja.agregar(ha);
        limpiarCamposHabitacion();
        listarHabitacion();
    }//GEN-LAST:event_btnAgregarHabActionPerformed

    private void btnEliminarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHotelActionPerformed
        int pos = objh.obtenerPosicion(Integer.parseInt(txtCodHotel.getText()));
        objh.eliminar(pos);
        listarHotel();
        limpiarCamposHotel();
    }//GEN-LAST:event_btnEliminarHotelActionPerformed

    private void btnEliminarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabActionPerformed
        int pos = obja.obtenerPosicion(Integer.parseInt(txtCodHabitacion.getText()));
        obja.eliminar(pos);
        listarHabitacion();
        limpiarCamposHabitacion();
    }//GEN-LAST:event_btnEliminarHabActionPerformed

    private void btnActualizarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHotelActionPerformed
        int posi=objh.obtenerPosicion(Integer.parseInt(txtCodHotel.getText()));
        String lugar=txtLugar.getText();
        String nombre=txtNomHotel.getText();
        String categoria = (String)cmbCategoria.getSelectedItem();
        int habitacion = Integer.parseInt(txthabitaciones.getText());
        int precio = Integer.parseInt(txtPrecio.getText());
        
        Hotel hote=objh.buscar(posi);
        hote.setLugar(lugar);
        hote.setNomHotel(nombre);
        hote.setCategoria(categoria);
        hote.setHabitaciones(habitacion);
        hote.setCostohotel(precio);
        objh.actualizar(posi, hote);
        limpiarCamposHotel();
        listarHotel();
    }//GEN-LAST:event_btnActualizarHotelActionPerformed

    private void btnActualizarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHabActionPerformed
        int pos=obja.obtenerPosicion(Integer.parseInt(txtCodHabitacion.getText()));
        int codVuelo=Integer.parseInt(txtCodHoHa.getText());
        String estado=txtEstadoHab.getText();
        
        Habitacion hab=obja.buscar(pos);
        hab.setCod_hotel(codVuelo);
        hab.setEstado(estado);
        
        obja.actualizar(pos, hab);
        limpiarCamposHabitacion();
        listarHabitacion();
    }//GEN-LAST:event_btnActualizarHabActionPerformed
    void limpiarCamposHotel(){
        txtCodHotel.setText("");
        txtCodHotel.requestFocus();
        txtNomHotel.setText("");
        txthabitaciones.setText("");
        txtPrecio.setText("");
    }
    void listarHotel() {
        DefaultTableModel dt = (DefaultTableModel) tableHotel.getModel();
        dt.setRowCount(0);
        for (Hotel hot : objh.data()) {
            Object h[] = {hot.getCodigo(), hot.getLugar(), hot.getNomHotel(), hot.getCategoria(), hot.getCostohotel(), hot.getHabitaciones()};
            dt.addRow(h);
        }
    }
    void limpiarCamposHabitacion(){
        txtCodHoHa.setText("");
        txtCodHabitacion.requestFocus();
        txtEstadoHab.setText("");
    }
    void listarHabitacion() {
        DefaultTableModel dt = (DefaultTableModel) tablaHabitacion.getModel();
        dt.setRowCount(0);
        for (Habitacion hab : obja.data()) {
            Object hb[] = {hab.getCod_hotel(), hab.getCod_habi(), hab.getEstado()};
            dt.addRow(hb);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHoteles().setVisible(true);
            }
        });
    }
    private void limpiaTabla(){
        for(int i=0;i<tableHotel.getRowCount();i++){
            for(int c=0;c<tableHotel.getColumnCount();c++){
                tableHotel.setValueAt("", i, c);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHab;
    private javax.swing.JButton btnActualizarHotel;
    private javax.swing.JButton btnAgregarHab;
    private javax.swing.JButton btnAgregarHotel;
    private javax.swing.JButton btnBuscarHab;
    private javax.swing.JButton btnBuscarHotel;
    private javax.swing.JButton btnEliminarHab;
    private javax.swing.JButton btnEliminarHotel;
    private javax.swing.JButton btnListarHab;
    private javax.swing.JButton btnListarHotel;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaHabitacion;
    private javax.swing.JTable tableHotel;
    private javax.swing.JTextField txtCodHabitacion;
    private javax.swing.JTextField txtCodHoHa;
    private javax.swing.JTextField txtCodHotel;
    private javax.swing.JTextField txtEstadoHab;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNomHotel;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txthabitaciones;
    // End of variables declaration//GEN-END:variables
}
