
package vista;

import clases.Viajero;
import javax.swing.table.DefaultTableModel;
import listas.listaViajeros;
/**
 *
 * @author Valia
 */
public class FormClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormClientes
     */
    listaViajeros viajero=new listaViajeros();
    
    public FormClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnListarCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidosCliente = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(102, 153, 255));
        setClosable(true);
        setMaximizable(true);
        setTitle("VentanaClientes");
        setVisible(true);
        getContentPane().setLayout(null);

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/buscar.png"))); // NOI18N
        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarCliente);
        btnBuscarCliente.setBounds(430, 92, 140, 59);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRES:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 77, 17);

        btnRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/agregar.png"))); // NOI18N
        btnRegistrarCliente.setText("REGISTRAR");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarCliente);
        btnRegistrarCliente.setBounds(430, 150, 140, 59);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("APELLIDOS:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 210, 86, 17);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COD", "NOMBRES", "APELLIDOS", "DNI", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 420, 500, 227);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 250, 33, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CÓDIGO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(78, 111, 64, 17);

        btnListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/listar.png"))); // NOI18N
        btnListarCliente.setText("LISTAR");
        btnListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarCliente);
        btnListarCliente.setBounds(80, 360, 130, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TELÉFONO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 300, 81, 17);
        getContentPane().add(txtCodCliente);
        txtCodCliente.setBounds(293, 101, 74, 30);
        getContentPane().add(txtNombreCliente);
        txtNombreCliente.setBounds(200, 150, 174, 30);
        getContentPane().add(txtApellidosCliente);
        txtApellidosCliente.setBounds(200, 200, 174, 30);
        getContentPane().add(txtDNI);
        txtDNI.setBounds(270, 250, 102, 20);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(250, 290, 119, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel1.setText("CLIENTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 22, 142, 40);

        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/actualizar.png"))); // NOI18N
        btnActualizarCliente.setText("ACTUALIZAR");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarCliente);
        btnActualizarCliente.setBounds(430, 270, 160, 59);

        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/delete.png"))); // NOI18N
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCliente);
        btnEliminarCliente.setBounds(430, 210, 140, 59);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 640, 2);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 350, 640, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        int cod=Integer.parseInt(txtCodCliente.getText());
        Viajero v=viajero.buscar(viajero.obtenerPosicion(cod));
        txtNombreCliente.setText(v.getNombre());
        txtApellidosCliente.setText(v.getApellidos());
        txtDNI.setText(""+v.getDni());
        txtTelefono.setText(v.getTelefono());
        txtCodCliente.setEditable(false);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        String nombre=txtNombreCliente.getText();
        String apel=txtApellidosCliente.getText();
        int dni=Integer.parseInt(txtDNI.getText());
        String tel=txtTelefono.getText();
        Viajero v=new Viajero(nombre, apel, dni, tel);
        viajero.agregar(v);
        listar();
        limpiarCampos();
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClienteActionPerformed
        listar();
    }//GEN-LAST:event_btnListarClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        int cod=Integer.parseInt(txtCodCliente.getText());
        int pos=viajero.obtenerPosicion(cod);
        Viajero x=viajero.buscar(pos);
        String nombre=txtNombreCliente.getText();
        String apel=txtApellidosCliente.getText();
        int dni=Integer.parseInt(txtDNI.getText());
        String tel=txtTelefono.getText();
        x.setNombre(nombre);x.setApellidos(apel);x.setDni(dni);x.setTelefono(tel);
        viajero.actualizar(pos, x);
        txtCodCliente.setEditable(true);
        listar();
        limpiarCampos();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        int cod=Integer.parseInt(txtCodCliente.getText());
        int pos=viajero.obtenerPosicion(cod);
        viajero.eliminar(pos);
        listar();
        limpiarCampos();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed
    
    /*metodos */
    void listar(){
        DefaultTableModel dt=(DefaultTableModel)tablaClientes.getModel();
        dt.setRowCount(0);
        for(Viajero vj: viajero.data()){
            Object v[]={vj.getCodigo(), vj.getNombre(), vj.getApellidos(), vj.getDni(), vj.getTelefono()};
            dt.addRow(v);
        }
    }
    void limpiarCampos(){
        txtCodCliente.setText("");txtNombreCliente.setText("");
        txtApellidosCliente.setText("");txtDNI.setText("");txtTelefono.setText("");
        txtCodCliente.requestFocus();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnListarCliente;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
